# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_manager', '0003_auto_20170618_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trash',
            name='location',
            field=models.CharField(default='/home/katya/.local/share/', max_length=30),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
