# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_manager', '0004_auto_20170621_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parallel_remove',
            field=models.BooleanField(default=False),
        ),
    ]
