# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_manager', '0005_task_parallel_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='regex',
            field=models.CharField(default='', max_length=30),
        ),
    ]
