# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_manager', '0006_auto_20170623_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='regex',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
